services:
  hlllogutilities:
    mem_limit: 512m
    restart: unless-stopped
    build: .
    volumes:
      - ./config.ini:/code/config.ini
      # TODO: Sessions is not created before started first (unless done manually)
      - ./sessions.db:/code/sessions.db

  hllu-pg:
    image: postgres:16
    container_name: hllu-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6543:5432"
    volumes:
      - hllu-pg-data:/var/lib/postgresql/data

volumes:
  hllu-pg-data:
